# Gradle properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use AndroidX
android.useAndroidX=true
android.builder.sdkDownload=true

# Enables namespacing for each library's R class so that its R class includes only the
# resources declared in the library itself and not from the library's dependencies
android.nonTransitiveRClass=true

# Kotlin style
kotlin.code.style=official
